### ISSUE TITLE
Info request

### ISSUE THREAD

**Issue by Fra9944** [AudioTK/AudioTK#2]
Is it possible to have a tutorial or a course on AudioToolkit with JUCE integration and design of analog hardware inside a plugin?

Is possible to use AudioTK for making a compressor or a Tube Equalizer?

Thank you in advance.

**Comment by mbrucher** [comment]
Hi!
There are a few light tutorials in the repo itself as well as a few plugins in the global project.
A forward compressor is very easy to do, and all my compressors and limiters are done this way.
Tube equalizers can also be done, you may have to write some modules if you want to have analog modelling of these modules, as I do for some of my plugins (like SD1, TS9, my preamps...)
