### ISSUE TITLE
What are the particular reasons for wrapping to Python than something else?

### ISSUE THREAD

**Issue by mavavilj** [AudioTK/AudioTK#3]
Perhaps a bit off-topic.

But based on the latest developments in C++, and the earlier with Lua etc., what are the particular things that led you to create wrappers for Python rather than something else? Boost.Python?

**Comment by mbrucher** [comment]
I worked in scientific Python for a long time, so using the Python tools to check the behavior of the C++ classes was the easiest. And I'm still doing that for the new plugins when generating the source code on the fly. I used SWIG for a while before moving to pybind11.
I don't know Lua or Julia to create the wrappers, although they shouldn't be too hard to create ;)

**Comment by mavavilj** [comment]
Food for thought: https://www.gnu.org/software/guile/

I've thought the Python to C++ interfaces seem very confusing, and this also confirms my belief that they're mostly implemented due to convention.
